window.data = [
  {
    make: "Honda",
    id: 1863,
    model: "Civic",
    msrp: 19750,
    isAvailable: true,
    numberAvailable: 3,
  },
  {
    make: "Honda",
    id: 1864,
    model: "Pilot",
    msrp: 31500,
    isAvailable: true,
    numberAvailable: 10,
  },
  {
    make: "Honda",
    id: 1865,
    model: "CR-V",
    msrp: 24450,
    isAvailable: true,
    numberAvailable: 15,
  },
  {
    make: "Honda",
    id: 1869,
    model: "Odyssey",
    msrp: 30690,
    isAvailable: true,
    numberAvailable: 8,
  },
  {
    make: "Honda",
    id: 1870,
    model: "Insight",
    msrp: 22950,
    isAvailable: false,
    numberAvailable: null,
  },
  {
    make: "Honda",
    id: 1875,
    model: "FCX Clarity",
    msrp: 33400,
    isAvailable: false,
    numberAvailable: null,
  },
  {
    make: "Honda",
    id: 1934,
    model: "Ridgeline",
    msrp: 29990,
    isAvailable: false,
    numberAvailable: null,
  },
  {
    make: "Honda",
    id: 2127,
    model: "Fit",
    msrp: 16190,
    isAvailable: true,
    numberAvailable: 3,
  },
  {
    make: "Honda",
    id: 2128,
    model: "Accord",
    msrp: 25000,
    isAvailable: true,
    numberAvailable: 4,
  },
  {
    make: "Honda",
    id: 2154,
    model: "Civic",
    msrp: 150.99,
    isAvailable: true,
    color: "Red",
    numberAvailable: 8,
  },
];
